busko_journey_homepage:
    pattern:  /index
    defaults: { _controller: BuskoJourneyBundle:Home:index }
    
busko_journey_Timetablehomepage:
    pattern:  /timetable
    defaults: { _controller: BuskoJourneyBundle:TimetableIndex:Timetable }
BuskoJourneyBundle_routes:
        resource: "@BuskoJourneyBundle/Resources/config/routing/routes.yml"
        prefix:   /routess
BuskoJourneyBundle_intermediates:
        resource: "@BuskoJourneyBundle/Resources/config/routing/intermediates.yml"
        prefix:   /intermediates
