busko_journey_homepage:
    pattern:  /index
    defaults: { _controller: BuskoJourneyBundle:Home:index }
    
busko_journey_Timetablehomepage:
    pattern:  /index
    defaults: { _controller: BuskoJourneyBundle:TimetableIndex:Timetable }
