parameters:
#    busko_site.example.class: Busko\SiteBundle\Example

services:
#    busko_site.example:
#        class: %busko_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
