BuskoEntityBundle_assistants:
       resource: "@BuskoEmployeeBundle/Resources/config/routing/assistants.yml"
       prefix:   /assistants
       
BuskoEntityBundle_drivers:
        resource: "@BuskoEmployeeBundle/Resources/config/routing/drivers.yml"
        prefix:   /drivers

BuskoEntityBundle_operators:
        resource: "@BuskoEmployeeBundle/Resources/config/routing/operators.yml"
        prefix:   /operators
BuskoEntityBundle_employees:
        resource: "@BuskoEmployeeBundle/Resources/config/routing/employees.yml"
        prefix:   /employees
