BuskoEntityBundle_assistants:
       resource: "@BuskoEmployeeBundle/Resources/config/routing/assistants.yml"
       prefix:   /assistants
       
BuskoEntityBundle_drivers:
        resource: "@BuskoEmployeeBundle/Resources/config/routing/drivers.yml"
        prefix:   /drivers

BuskoEntityBundle_operators:
        resource: "@BuskoEmployeeBundle/Resources/config/routing/operators.yml"
        prefix:   /operators
        
BuskoEntityBundle_admins:
        resource: "@BuskoEmployeeBundle/Resources/config/routing/administrators.yml"
        prefix:   /admins
drivers_add:
    pattern:  /driverAdd
    defaults: { _controller: "BuskoEmployeeBundle:DriversAdd:register" }
    
    
assistant_add:
    pattern:  /assistantAdd
    defaults: { _controller: "BuskoEmployeeBundle:AssistantAdd:register" }
