parameters:
#    ground_zero_registration.example.class: GroundZero\EmployeeBundle\Example

services:
    groundZero_user.registration.form.type:
        class: Busko\EmployeeBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: groundZero_user_registration }
    groundZero_user.profile.form.type:
        class: Busko\EmployeeBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: groundZero_user_profile }
