intermediates:
    pattern:  /
    defaults: { _controller: "BuskoJourneyBundle:Intermediates:index" }

intermediates_show:
    pattern:  /{id}/{rId}/show
    defaults: { _controller: "BuskoJourneyBundle:Intermediates:show" }

intermediates_new:
    pattern:  /new
    defaults: { _controller: "BuskoJourneyBundle:Intermediates:new" }

intermediates_create:
    pattern:  /create
    defaults: { _controller: "BuskoJourneyBundle:Intermediates:create" }
    requirements: { _method: post }
intermediates_save:
    pattern:  /{rId}/save
    defaults: { _controller: "BuskoJourneyBundle:Intermediates:createRouteSave" }
    

intermediates_createInter:
    pattern: /{rId}/createInter
    defaults: { _controller: "BuskoJourneyBundle:Intermediates:createRoute" }

intermediates_edit:
    pattern:  /{id}/{rId}/edit
    defaults: { _controller: "BuskoJourneyBundle:Intermediates:edit" }

intermediates_update:
    pattern:  /{id}/{rId}/update
    defaults: { _controller: "BuskoJourneyBundle:Intermediates:update" }
    requirements: { _method: post|put }

intermediates_delete:
    pattern:  /{id}/{rId}/delete
    defaults: { _controller: "BuskoJourneyBundle:Intermediates:delete" }
    requirements: { _method: post|delete }
