branches:
    pattern:  /
    defaults: { _controller: "BuskoBranchBundle:BusPage:branchPage" }

busko_branch_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: BuskoBranchBundle:Default:index }

branch_page:
    pattern: /branchPage
    defaults: { _controller: BuskoBranchBundle:BranchPage:branchPage }

create_branch:
    pattern: /createBranch
    defaults: { _controller: BuskoBranchBundle:BranchCreation:createBranch }
    
edit_branch:
    pattern: /{id}/edit
    defaults: { _controller: BuskoBranchBundle:BranchPage:edit }

update_branch:
    pattern: /{id}/update
    defaults: { _controller: BuskoBranchBundle:BranchPage:update }
    requirements: { _method: post|put }

submit_branch:
    pattern: /submitBranch
    defaults: { _controller: BuskoBranchBundle:BranchSubmission:submitBranch }

confirm_branch:
    pattern: /confirmBranch
    defaults: { _controller: BuskoBranchBundle:BranchConfirmation:confirmBranch }

view_branch:
    pattern: /viewBranch
    defaults: { _controller: BuskoBranchBundle:BranchView:viewBranch }

delete_branch:
    pattern: /deleteBranch
    defaults: { _controller: BuskoBranchBundle:BranchDeletion:deleteBranch }
    
view_details:
    pattern: /{id}/viewdetails
    defaults: { _controller: BuskoBranchBundle:BranchPage:viewDetails }