admins:
    pattern:  /
    defaults: { _controller: "BuskoEmployeeBundle:Admin:index" }

admins_show:
    pattern:  /{id}/show
    defaults: { _controller: "BuskoEmployeeBundle:Admin:show" }

admins_edit:
    pattern:  /edit
    defaults: { _controller: "BuskoEmployeeBundle:Admin:edit"}


admins_create:
    pattern:  /create
    defaults: { _controller: "BuskoEmployeeBundle:Admin:create" }
admins_add:
    pattern:  /add
    defaults: { _controller: "BuskoEmployeeBundle:Admin:register" }   



admins_update:
    pattern:  /update
    defaults: { _controller: "BuskoEmployeeBundle:Admin:update" }
    requirements: { _method: post|put }

admin_delete:
    pattern:  /delete
    defaults: { _controller: "BuskoEmployeeBundle:Admin:delete" }
    requirements: { _method: post|delete }
