operators:
    pattern:  /
    defaults: { _controller: "BuskoEmployeeBundle:Operator:index" }

operators_show:
    pattern:  /{id}/show
    defaults: { _controller: "BuskoEmployeeBundle:Operator:show" }

operators_edit:
    pattern:  /edit
    defaults: { _controller: "BuskoEmployeeBundle:Operator:edit"}


operators_create:
    pattern:  /create
    defaults: { _controller: "BuskoEmployeeBundle:Operator:create" }
    
operators_add:
    pattern:  /add
    defaults: { _controller: "BuskoEmployeeBundle:Operator:register" }
 
operators_update:
    pattern:  /update
    defaults: { _controller: "BuskoEmployeeBundle:Operator:update" }
    requirements: { _method: post|put }

operator_delete:
    pattern:  /delete
    defaults: { _controller: "BuskoEmployeeBundle:Operator:delete" }
    requirements: { _method: post|delete }
