intermediates:
    pattern:  /
    defaults: { _controller: "BuskoEntityBundle:Intermediates:index" }

intermediates_show:
    pattern:  /{id}/show
    defaults: { _controller: "BuskoEntityBundle:Intermediates:show" }

intermediates_new:
    pattern:  /new
    defaults: { _controller: "BuskoEntityBundle:Intermediates:new" }

intermediates_create:
    pattern:  /create
    defaults: { _controller: "BuskoEntityBundle:Intermediates:create" }
    requirements: { _method: post }

intermediates_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BuskoEntityBundle:Intermediates:edit" }

intermediates_update:
    pattern:  /{id}/update
    defaults: { _controller: "BuskoEntityBundle:Intermediates:update" }
    requirements: { _method: post|put }

intermediates_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BuskoEntityBundle:Intermediates:delete" }
    requirements: { _method: post|delete }
